export type UserRole = 'ceo' | 'it_admin' | 'consultant';

export type FollowUpSymbol = '*' | '+' | '-' | '.' | '✓' | '';

export interface FollowUpStatusCode {
  code: FollowUpSymbol;
  symbol: string;
  label: string;
  meaning: string;
  colorClass: string;
  badgeClass: string;
  bgClass: string;
  textColor: string;
  borderColor: string;
}

export interface User {
  id: string;
  username: string;
  fullName: string;
  consultantCode: string;
  role: UserRole;
  password?: string;
  avatar?: string;
  phone?: string;
  branch?: string;
}

export interface ReportRow {
  id: string;
  rowNumber: number;
  clientName: string; // نام و نام خانوادگی کارفرما
  activityField: string; // زمینه فعالیت / صنف
  personnelCount?: number | string; // تعداد پرسنل (اختیاری)
  phone: string; // شماره تماس
  address: string; // آدرس
  employerConcern: string; // دغدغه کارفرما (از لیست ۲۵ تایی)
  followUp1: string; // پیگیری ۱
  followUp2: string; // پیگیری ۲
  followUp3: string; // پیگیری ۳
  followUp4: string; // پیگیری ۴
  followUpResult: string; // نتیجه پیگیری
  meetingTopic: string; // موضوع جلسه
  notes?: string;
}

export interface DailyReport {
  id: string;
  consultantId: string;
  consultantName: string;
  consultantCode: string;
  guild: string; // صنف کلی گزارش
  dateShamsi: string; // تاریخ شمسی
  dayOfWeekShamsi: string; // روز هفته
  createdAt: string; // ISO string
  submittedAt: string; // ساعت ارسال
  status: 'submitted' | 'approved' | 'needs_review';
  personalOpinion: string; // نظر شخصی مشاور درباره فعالیت روزانه
  rows: ReportRow[];
  managerFeedback?: string;
  managerRating?: number; // 1 to 5 stars
  reviewedAt?: string;
  updatedAt?: string; // ISO string of last edit/follow-up modification
}

export interface ArchiveRecord {
  id: string;
  fileName: string; // e.g. "گزارش_روزانه_دوشنبه_1403-06-09.xlsx"
  dateShamsi: string;
  dayOfWeek: string;
  timestamp: string;
  totalConsultants: number;
  totalClientsContacted: number;
  topConcerns: { name: string; count: number }[];
  reports: DailyReport[];
  autoGenerated: boolean;
}

export interface AIAnalysisResult {
  summary: string;
  overallScore: number;
  topTrends: string[];
  consultantEvaluations: {
    consultantName: string;
    consultantCode: string;
    performanceRating: string;
    strengths: string[];
    weaknessesOrFollowUps: string[];
    aiRecommendation: string;
  }[];
  marketOpportunities: string[];
  strategicActionItems: string[];
}

export interface ManagerDirective {
  id: string;
  targetConsultantId: string; // 'all' or specific consultantId/code
  targetConsultantName?: string;
  authorId?: string;
  authorName: string;
  content: string; // e.g. "پرونده کریمی رو اولویت بده"
  priority: 'high' | 'normal';
  createdAt: string;
  dateShamsi: string;
}

export interface UpcomingFollowUpItem {
  reportId: string;
  reportDateShamsi: string;
  createdAt: string;
  guild: string;
  rowNumber: number;
  rowId: string;
  clientName: string;
  activityField: string;
  phone: string;
  address: string;
  employerConcern: string;
  meetingTopic: string;
  followUp1: string;
  followUp2: string;
  followUp3: string;
  followUp4: string;
  followUpResult: string;
  nextStepNumber: number; // 2, 3, or 4
  elapsedDays: number;
  daysRemaining: number;
  statusCategory: 'today' | 'overdue' | 'future';
}


